name: Publish
on:
  workflow_dispatch: # Allow running the workflow manually from the GitHub UI
  release:
    types:
      - published    # Run the workflow when a new GitHub release is published

jobs:
  release:
    name: Release
    strategy:
      matrix:
        os: [windows-latest]
        target: [win-x64, win-x86]
      
    runs-on: ${{matrix.os}}
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Get all history to allow automatic versioning using MinVer
        
    # Install the .NET SDK
    #- name: Setup .NET
    #  uses: actions/setup-dotnet@v3
      
    # Publish as single exe
    - name: Publish
      run: |
        release_name="ReolinkRestart-${{github.ref_name}}-${{matrix.target}}"
        
        dotnet publish -o "$release_name" --configuration Release --runtime ${{matrix.target}} -p:PublishSingleFile=true --no-self-contained

    # Upload assets to release
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: "ReolinkRestart*.exe"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
