name: Publish
on:
  workflow_dispatch: # Allow running the workflow manually from the GitHub UI
  release:
    types:
      - published    # Run the workflow when a new GitHub release is published

jobs:
  build:
    
    env:
      BUILD_CONFIG: 'Release'
      
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Get all history to allow automatic versioning using MinVer
        
    # Install the .NET SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      
    # Publish as single exe
    - name: Publish
      run: dotnet publish --configuration $BUILD_CONFIG -runtime win-x86 -p:PublishSingleFile=true --no-self-contained

    # Upload assets to release
    #- name: Upload Release Asset
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #  run:
    #    gh release upload <release_tag> <a_file>
