name: Publish
on:
  workflow_dispatch: # Allow running the workflow manually from the GitHub UI
  release:
    types:
      - published    # Run the workflow when a new GitHub release is published

jobs:
  release:
    name: Release
    strategy:
      matrix:
        os: [windows-latest]
        target: [win-x64, win-x86]
      
    runs-on: ${{matrix.os}}

    steps:

    - name: Set environment variable
      shell: bash
      run: echo "APP_NAME=ReolinkRestart" >> $GITHUB_ENV

    - name: Set environment variable
      shell: bash
      run: echo "PUBLISH_DIR=${{env.APP_NAME}}-${{github.ref_name}}-${{matrix.target}}" >> $GITHUB_ENV

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Get all history to allow automatic versioning using MinVer

    - name: Publish
      run: dotnet publish -o "${{env.PUBLISH_DIR}}" --configuration Release --runtime ${{matrix.target}} -p:PublishSingleFile=true --no-self-contained
    
    - name: Rename executable
      shell: bash
      run: mv '${{env.PUBLISH_DIR}}/${{env.APP_NAME}}.exe' '${{env.PUBLISH_DIR}}/${{env.PUBLISH_DIR}}.exe'

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifact
        path: ./
    
    - name: Upload Release Assets
      uses: softprops/action-gh-release@v1
      with:
        files: ${{env.PUBLISH_DIR}}/${{env.PUBLISH_DIR}}.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
